### PR TITLE
Add TRADFRI Fyrtur blinds and open/close remote drivers 

### PR DESCRIPTION
**Pull request by lucasvdh**
Add support for the new TRAFRI Fyrtur (404.081.96) automated blinds by IKEA. 

## TODO
- [x] Implement custom setters using `closuresWindowCovering` cluster
- [ ] Find out the Kadrilj `deviceId` and `profileId`

### CODE REVIEW

**Comment by lucasvdh** [comment]
The `onoff` capability with cluster `genBasic` doesn't work for the blinds. It's more likely that the blinds need to be sent commands from the `closuresWindowCovering` cluster. 

However, there is no mapping for a Homey capability to this cluster yet in the `homey-meshdriver` package. So one of two things will probably need to happen: 
- a Homey capability needs to be mapped to `closuresWindowCovering` in the meshdriver package 
- a custom implementation needs to be made for the `roller_blind` device

I'll probably try and get the blinds working with an implementation in the device, maybe someone else can then refactor it to the `homey-meshdriver` package?

**Comment by lucasvdh** [comment]
Got everything working :tada: Lets hope this makes the people who already have the new roller blinds happy.

### Notes

#### Icons
Only thing which you might want to have a look at is the icons. The pairing icon for the blinds could've been a bit better. Also the icon I made for the blinds is not how it is originally depicted in the instruction manual, but I think this icon better represents the blinds. The icon from the manual would have been to large (or the buttons on which it's displayed too smal) for it to be recognizable.

#### Repeater
I don't know if it's required that you add the repeater device before you add the blinds itself. The instruction manual from IKEA says that the blinds **will not** function without having the repeater configured. I don't see why that would be the case but I added it as a device to my Homey just to be sure.

#### Homey Meshdriver update
It would be better to refactor the custom implementation of the `windowcoverings_state` capability to the `homey-meshdriver` package. Maybe the maintainer of the package from Athom can do this?

**Comment by lucasvdh** [comment]
The new open close remote driver isn't working yet, want me to move it to a separate PR?

**Comment by TvAnton** [comment]
Hi i have a fyrtur at home how do i get it to work!
Sorry a homey beginner:) 

Thanks for your amazing work

**Comment by lucasvdh** [comment]
> Hi i have a fyrtur at home how do i get it to work!
> Sorry a homey beginner:)
> 
> Thanks for your amazing work

You can just install the version of the app at [lucasvdh/com.ikea.tradfri](https://github.com/lucasvdh/com.ikea.tradfri) with the [athom-cli](https://apps.developer.athom.com/tutorial-Getting%20Started.html). If you don't know how to do this I'm afraid you'll just have to wait until this pull request is accepted and the original app is updated.

**Comment by lucasvdh** [comment]
Having some trouble getting the open/close remote device working with the driver I wrote for it. Opened the issue referenced above.

**Comment by lordradon** [comment]
Hi, sorry to disturb. But any eta when the blinds are up and running on this ikea app?
Appreciate the work you're doing.

**Comment by harmstellinga** [comment]
Great work @lucasvdh, up and down in HOMEY already works fine, still Some ..... op de i zetten
i think.
Will the remote also be implented.

**Comment by lucasvdh** [comment]
@lordradon the driver for the blinds is already working, if you want you can install this version manually. As to the question of when this PR will be accepted, I cannot say.

@harmstellinga I've concluded that the ZigBee command `goToLiftValue` does not work for the IKEA blinds and I'll remove the corresponding Homey capability from the driver in this PR once I have some time.

@lordradon @harmstellinga the driver for the open/close remote is included in this PR but I haven't managed to get it working because of [this issue](https://github.com/athombv/homey-apps-sdk-issues/issues/89). My guess is that the PR won't be accepted until this issue is fixed by Athom.

**Comment by lordradon** [comment]
Yes thanks, up, down and idle works great. Got the unknown zigbee as you have said, for the remote.

Will there be a possibility for sliding up and down incrementally, like a dimmer slider? 
Right now, flow to get it 50% is down then idle after 10secs

**Comment by lucasvdh** [comment]
@lordradon I've concluded that the ZigBee command `goToLiftValue` does not work for the IKEA blinds and I'll remove the corresponding Homey capability from the driver in this PR once I have some time. So, no. You could try to figure out the timings yourself though.

**Comment by RobinBol** [comment]
Hi @lucasvdh! Thanks a lot for your PR, I was so free to use parts of your code for the implementation of the Fyrtur and Kadrilj drivers (see [here](https://github.com/athombv/com.ikea.tradfri/pull/78)). Additionally I have added a system capability to [homey-meshdriver](https://github.com/athombv/node-homey-meshdriver/commit/3736bfade542dcf190b1272ed49947948595d15b).

Short question, how did you find the `deviceId`, `productId` and `profileId` for the Kadrilj driver? Are you certain these are correct?

Thanks!

**Comment by lucasvdh** [comment]
@RobinBol, great to hear!

Regarding the `deviceId` and `pofileId` of the KADRILJ blinds, I don't know these. I'm 100% about the FYRTUR blinds but I don't know of anyone who has the KADRILJ blinds, so those still need to be verified  :man_shrugging:.
The `productId` was a guess based on the English name for the product on the IKEA website because the name (`productId`) of the FYRTUR blinds matched the website exactly.

I'll try to give the PR a test drive tonight!

**Comment by RobinBol** [comment]
Ok, thank you for the information! I think the KADRILJ `deviceId` and `profileId` are identical to FYRTUR. The `productId` is indeed a good guess, but I am hesitant to release that driver specifically if we have no confirmation that it is indeed the correct `productId`. We have been able to get our hands on a FYRTUR but not a KADRILJ unfortunately.

**Comment by lucasvdh** [comment]
Guess the KADRILJ driver will have to wait a bit until some can provide the `productId` then.

**Comment by RobinBol** [comment]
I will close this PR since it has been replaced in the meantime.

**Pull request closed without merging**
