### PR TITLE
Add RGB bulb support

### PR DESCRIPTION
**Pull request by RobinBol**

### CODE REVIEW

**Comment by casperboone** [comment]
Maybe I'm missing something and this makes perfect sense, but I had to an `npm install` to fix a problem where `homey-meshdriver` could not be found. Reproduced it a couple of times.

image

**Comment by casperboone** [comment]
@RobinBol Unfortunately the colors do not work yet (they all result in white). Probably a conversion error from hue to xy, dealt with a few working on my pr as well hehe.

Also, after pairing the following is logged:
```
2017-09-18 21:53:31 [err] [ManagerDrivers] [rgb_bulb] [1] { Error: request unsuccess: 134
    at Object.<anonymous> (/opt/homey-client/system/manager/ManagerApps/jsonfns.js:1:1040)
    at JSON.parse (<anonymous>)
    at Object.jsonToObject (/opt/homey-client/system/manager/ManagerApps/jsonfns.js:1:938)
    at function.e.apply.s.args.map.s (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/HomeyClient.js:1:1401)
    at Array.map (<anonymous>)
    at HomeyClient._onMessage (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/HomeyClient.js:1:1386)
    at emitTwo (events.js:125:13)
    at process.emit (events.js:213:7)
    at emit (internal/child_process.js:774:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9) message: 'request unsuccess: 134' }
2017-09-18 21:53:31 [err] [ManagerDrivers] [rgb_bulb] [1] { Error: request unsuccess: 134
    at Object.<anonymous> (/opt/homey-client/system/manager/ManagerApps/jsonfns.js:1:1040)
    at JSON.parse (<anonymous>)
    at Object.jsonToObject (/opt/homey-client/system/manager/ManagerApps/jsonfns.js:1:938)
    at function.e.apply.s.args.map.s (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/HomeyClient.js:1:1401)
    at Array.map (<anonymous>)
    at HomeyClient._onMessage (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/HomeyClient.js:1:1386)
    at emitTwo (events.js:125:13)
    at process.emit (events.js:213:7)
    at emit (internal/child_process.js:774:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9) message: 'request unsuccess: 134' }
2017-09-18 21:53:37 [err] [ManagerDrivers] [rgb_bulb] [1] { Error: request unsuccess: 134
    at Object.<anonymous> (/opt/homey-client/system/manager/ManagerApps/jsonfns.js:1:1040)
    at JSON.parse (<anonymous>)
    at Object.jsonToObject (/opt/homey-client/system/manager/ManagerApps/jsonfns.js:1:938)
    at function.e.apply.s.args.map.s (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/HomeyClient.js:1:1401)
    at Array.map (<anonymous>)
    at HomeyClient._onMessage (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/HomeyClient.js:1:1386)
    at emitTwo (events.js:125:13)
    at process.emit (events.js:213:7)
    at emit (internal/child_process.js:774:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9) message: 'request unsuccess: 134' }
```
Not sure what it's supposed to request, but it fails, maybe it can help you 😄.

**Comment by RobinBol** [comment]
Thanks, somehow my dependencies got messed up, added them again. Strange 134 status code, was the bulb powered on at the time? Maybe a bit out of range? Did not ran into them myself.

**Comment by casperboone** [comment]
@RobinBol Was powered on, paired my second rgb bulb, and got the same. Both about 3 meters from Homey, no obstacles, also no other failures, so I don't think the range was the problem.

**Pull request merged**
