### PR TITLE
Adds support for KADRILJ rollerblind

### PR DESCRIPTION
**Pull request by RobinBol**
Supported functionality:
- Moving blinds up and down to a relative percentage using a dim slider
- Displaying current battery levels

Todo's
- [X] Add developer contribution
- [x] Device icons
- [x] Learnmode icons

_NOTE: depends on https://github.com/athombv/com.ikea.tradfri/pull/79_

_NOTE 2: waiting for verification of `productId`/`deviceId` and `profileId`_

### CODE REVIEW

**Comment by lucasvdh** [comment]
@RobinBol did you manage to figure out how you can set the configured min top (`installedOpenLimitLiftCm`) and max bottom (`installedClosedLimitLiftCm`) that the blinds roll out? 

If the answer is no and they aren't writable, maybe Homey can manage these limits. Because you managed to get the `goToLiftPercentage` working you could create two settings for the FYRTUR and KADRILJ blinds:

- `min top` - A value in centimeters (because the length of the blinds is always 195cm) or a percentage which describes the minimum length/amount that the blinds will stay rolled out.
- `max bottom` - A value in centimeters or a percentage which describes the maximum length/amount that the blinds will roll.

Then in the logic which sends the `goToLiftPercentage` command to the device you could check if the provided value does not exceed any of the limits and if it does that you just default to the configured limit.

My preference would definitely go to using centimeters as a unit as it would be easy for a user to accurately measure this. Also, if you do manage to write these attributes to the device I think it'd still be better to store these settings as centimeters and convert them to whatever unit the device expects before writing them.

Hope you manage to figure this one out, would be a **great** addition imho.

**Comment by RobinBol** [comment]
The `installedOpenLimit - Lift` and `installedClosedLimit - Lift` are read-only properties as described [here](http://www.zigbee.org/wp-content/uploads/2014/10/07-5123-06-zigbee-cluster-library-specification.pdf) on page 7-51.

If I understand your problem correctly, you want to provide a min - max range for the blinds to go up and down? This is supported by the device itself, it can be calibrated by moving it to a desired position, then double-clicking either the up or down button. It will move slightly up and slightly down and from then on it is calibrated to that position as being full open.

Therefore I don't think we need to implement an additional calibration feature in Homey itself. Please let me know if I understood you correctly.

**Comment by lucasvdh** [comment]
I guess that works .. 

The reason that I wanted this; because I've got certain space restrictions, I needed to mount my blinds backwards in a window frame. Which means the buttons are facing the back side/wall of the window frame and I have to take the entire thing out to be able to access the buttons. This doesn't make for easy configuration :neutral_face:

**Comment by JackDaniel007** [comment]
I get the following error if I want to install via cli :(

✓ Pre-processing app...
✓ Running plugins...
✓ Running plugin `zigbee`...
✓ Installing homey-meshdriver@latest...
✓ Installation complete
✓ Plugin `zigbee` finished
✓ Validating app...
✖ Homey App did not validate against level `debug`:
[
    {
        "keyword": "enum",
        "dataPath": ".drivers[13].energy.batteries[0]",
        "schemaPath": "#/properties/drivers/items/properties/energy/properties/batteries/items/enum",
        "params": {
            "allowedValues": [
                "LS14250",
                "AA",
                "AAA",
                "A27",
                "PP3",
                "CR123A",
                "CR2",
                "CR1632",
                "CR2032",
                "CR2450",
                "CR2477"
            ]
        },
        "message": "should be equal to one of the allowed values"
    }
]
Not installing, please fix the validation issues first

**Comment by RobinBol** [comment]
> I get the following error if I want to install via cli :(
> 
> ✓ Pre-processing app...
> ✓ Running plugins...
> ✓ Running plugin `zigbee`...
> ✓ Installing homey-meshdriver@latest...
> ✓ Installation complete
> ✓ Plugin `zigbee` finished
> ✓ Validating app...
> ✖ Homey App did not validate against level `debug`:
> [
> {
> "keyword": "enum",
> "dataPath": ".drivers[13].energy.batteries[0]",
> "schemaPath": "#/properties/drivers/items/properties/energy/properties/batteries/items/enum",
> "params": {
> "allowedValues": [
> "LS14250",
> "AA",
> "AAA",
> "A27",
> "PP3",
> "CR123A",
> "CR2",
> "CR1632",
> "CR2032",
> "CR2450",
> "CR2477"
> ]
> },
> "message": "should be equal to one of the allowed values"
> }
> ]
> Not installing, please fix the validation issues first

Did you update athom-cli to the latest?

**Comment by JackDaniel007** [comment]
> > I get the following error if I want to install via cli :(
> > ✓ Pre-processing app...
> > ✓ Running plugins...
> > ✓ Running plugin `zigbee`...
> > ✓ Installing homey-meshdriver@latest...
> > ✓ Installation complete
> > ✓ Plugin `zigbee` finished
> > ✓ Validating app...
> > ✖ Homey App did not validate against level `debug`:
> > [
> > {
> > "keyword": "enum",
> > "dataPath": ".drivers[13].energy.batteries[0]",
> > "schemaPath": "#/properties/drivers/items/properties/energy/properties/batteries/items/enum",
> > "params": {
> > "allowedValues": [
> > "LS14250",
> > "AA",
> > "AAA",
> > "A27",
> > "PP3",
> > "CR123A",
> > "CR2",
> > "CR1632",
> > "CR2032",
> > "CR2450",
> > "CR2477"
> > ]
> > },
> > "message": "should be equal to one of the allowed values"
> > }
> > ]
> > Not installing, please fix the validation issues first
> 
> Did you update athom-cli to the latest?

now :) , and now only this message comes to an end, is that ok?

✓ Pre-processing app...
✓ Running plugins...
✓ Running plugin `zigbee`...
✓ Installing homey-meshdriver@latest...
✓ Installation complete
✓ Plugin `zigbee` finished
✓ Validating app...
✓ Homey App validated successfully against level `debug`
✓ Packing Homey App...
 — App size: 1.8 MB
✓ Installing Homey App on `DaHam` (https://192-168-1-61.homey.homeylocal.com)...
✖ [
    {
        "keyword": "enum",
        "dataPath": ".drivers[13].energy.batteries[0]",
        "schemaPath": "#/properties/drivers/items/properties/energy/properties/batteries/items/enum",
        "params": {
            "allowedValues": [
                "LS14250",
                "AA",
                "AAA",
                "A27",
                "PP3",
                "CR123A",
                "CR2",
                "CR1632",
                "CR2032",
                "CR2450",
                "CR2477"
            ]
        },
        "message": "should be equal to one of the allowed values"
    }
]

**Comment by RobinBol** [comment]
Something is still not up to date, allowedValue `OTHER` has been added and should be valid.

**Comment by JackDaniel007** [comment]
> Something is still not up to date, allowedValue `OTHER` has been added and should be valid.

i have now changed from my mac to the windows pc, but the same :(

C:\Users\001528265\Downloads\com.ikea.tradfri-alpha>athom app install
✓ Pre-processing app...
✓ Running plugins...
✓ Running plugin `zigbee`...
✓ Installing homey-meshdriver@latest...
✓ Installation complete
✓ Plugin `zigbee` finished
✓ Validating app...
✓ Homey App validated successfully against level `debug`
? Choose an active Homey: DaHam (online)
You have selected `DaHam` as your active Homey.
✓ Packing Homey App...
 — App size: 1.8 MB
✓ Installing Homey App on `DaHam` (http://192.168.1.61:80)...
× [
    {
        "keyword": "enum",
        "dataPath": ".drivers[13].energy.batteries[0]",
        "schemaPath": "#/properties/drivers/items/properties/energy/properties/batteries/items/enum",
        "params": {
            "allowedValues": [
                "LS14250",
                "AA",
                "AAA",
                "A27",
                "PP3",
                "CR123A",
                "CR2",
                "CR1632",
                "CR2032",
                "CR2450",
                "CR2477"
            ]
        },
        "message": "should be equal to one of the allowed values"
    }
]

C:\Users\001528265\Downloads\com.ikea.tradfri-alpha>

**Comment by mapulu** [comment]
I think it has nothing todo with the athom-cli
Homey needs to be at least v3.0.0

**Comment by RobinBol** [comment]
My bad, @mapulu is right, now the validation of the app breaks in Homey.

I have removed the dependency on Homey v3.0.0, now you should be able to run it on your Homey.

**Comment by JackDaniel007** [comment]
thx, now works perfecti 
is it also planned to support the tradfri open/close remote?
Hersteller ID: KE
Produkt ID: TRADFRI open/close remote
Geräte ID: 515
Profil ID 260
Netzwerkadresse 0x000d6ffffe9a18b2

**Comment by lucasvdh** [comment]
@JackDaniel007 there is an issue blocking this. See https://github.com/athombv/homey-apps-sdk-issues/issues/89

**Comment by Zekcode** [comment]
Just installed this, and looks like it's working :) thanks for a lot of hard work. i appreciate it!
Looking forward to the final release 👍 🥇 
IMG_0004

**Comment by pellz0r** [comment]
Is the battery level supposed to work right now? Because it only says 0% for me. Everything else seems to be working fine.

**Comment by JackDaniel007** [comment]
> Is the battery level supposed to work right now? Because it only says 0% for me. Everything else seems to be working fine.

no problems here, on my two roller blinds shows the correct battery level

**Comment by RobinBol** [comment]
Battery level was working fine on our Fyrtur as well.

**Comment by pellz0r** [comment]
I did notice one thing during installation that might be related.
"Warning: drivers.rollerblind_fyrtur is missing an array 'energy.batteries' because the capability measure_battery is being used. Specifying the type of battery will be required in the future."

Could that be the reason? That log line didn't appear during JackDaniel007's installation mentioned abouve.

**Comment by RobinBol** [comment]
No that is just a dev warning, that does not affect battery reporting.

**Comment by Zekcode** [comment]
can confirm that, battery status are not working here. :)

and i lost the signal to the blind 2 minuts after i connected them. :)

**Comment by pellz0r** [comment]
Battery status suddenly started to work. I ran the blind up and down a couple of times. Maybe it triggered the blind to send an updated battery level value.

**Comment by RobinBol** [comment]
Product ids are confirmed, thanks!

**Pull request closed without merging**
