### PR TITLE
Add support for TRADFRI bulb E27 CWS opal 600lm

### PR DESCRIPTION
**Pull request by casperboone**
This PR is an attempt to add support for the TRADFRI bulb E27 CWS opal 600lm, the RGB bulb.

Everything works 🎉 , but the code is not how it's supposed to be. I've managed to get it working to turn on/off the bulbs, to dim them and to change the color (funny detail: the remote that comes with it only allows cycling between 8 colors, not even including a green color, but now it's possible to pick any color 😄  ).

However, the color is changed with the `moveToColor` command. `moveToColor` uses colors in the CIE 1931 space (XY). So far, there is no capability that supports this in the meshdriver. For now, I've quickly edited [capabilities/light_hue/lightingColorCtrl.js](https://github.com/casperboone/com.ikea.tradfri/blob/9612ab314b3528450167a701523bb379f819b26d/node_modules/homey-meshdriver/lib/zigbee/system/capabilities/light_hue/lightingColorCtrl.js) and used a color conversion package to convert from a hue value to a XY color.

I have a few questions:
* I can make [capabilities/light_hue/lightingColorCtrl.js](https://github.com/casperboone/com.ikea.tradfri/blob/9612ab314b3528450167a701523bb379f819b26d/node_modules/homey-meshdriver/lib/zigbee/system/capabilities/light_hue/lightingColorCtrl.js) cleaner (doing the color conversion math manually) and PR it to `homey-meshdriver`. However, I can of course not use the capability name `light_hue` for it. Maybe it's an idea to introduce a new capability `light_color` that has the same colorwheel but gives RGB values? Or is there a better way to do this?
* If I do use a new capability, how can we make sure we still have the colorwheel in the cards?

Because of the large diff due to the color conversion package, here is a list of the files that are useful to review:
* [app.json](https://github.com/athombv/com.ikea.tradfri/pull/10/files#diff-6a1b6963e828b69fcc667e3c45df78bb)
* [drivers/rgb_bulb/device.js](https://github.com/athombv/com.ikea.tradfri/pull/10/files#diff-f72ac1fee15b4cf7e10462051c949bcc)
* [node_modules/homey-meshdriver/lib/zigbee/system/capabilities/light_hue/lightingColorCtrl.js](https://github.com/athombv/com.ikea.tradfri/pull/10/files#diff-3c223ef6aebb3500c3e5ef53c0f9838b)

### CODE REVIEW

**Comment by RobinBol** [comment]
Hi! Thanks for you contribution, how do you manage to switch between color and regular light mode? I think the current implementation only allows for color control, and not temperature, am I right?

**Comment by casperboone** [comment]
@robinbol That's right, I'm not sure if it's actually possible to control the color temperature separately. I think that the white-ish light modes are just colors (the white colors are also available within the color space used, just not in the hue based color wheel atm).

**Comment by RobinBol** [comment]
I create a bit more generic solution for now which also support light temperature, will be updated soon!

Thanks:)

**Comment by casperboone** [comment]
@RobinBol Cool, looking forward to it.

**Comment by RobinBol** [comment]
(you can already test if you want, just side load this branch onto your Homey: https://github.com/athombv/com.ikea.tradfri/pull/17)

**Pull request closed without merging**
