### PR TITLE
feat: update to SDKv3

### LINKED ISSUE #90: Adding dimmer tradfri ikea art# 704.085.95
Hello,

I bought the dimmer 704.085.95 for Tradfri last weekend. However in the app for homey this modules is not implemented yet. Properbly it is a brand new device, but so easy to use. could you add this device to the collection of tradfri devices.
thanks in advance.

Marcel

### LINKED ISSUE #91: Please add support TRADFRI open/close remote
Please add support of TRADFRI open/close remote

### PR DESCRIPTION
**Pull request by RobinBol**
Updates to SDKv3 and adds support for:
- Wireless Dimmer (fixes #90 )
- Motion Sensor
- Remote Control (5-button)
- Up/Down Remote Control (fixes #91 )

### CODE REVIEW

**Comment by weusthofm** [comment]
Hallo,
Hoe krijg ik de laatste versie 1.73 in mijn homey gelsden. Ik kan slechts versie 1.6.3 inlezen. Graag info hoe deze laatste versie kan inlezen in homey.

**Comment by RobinBol** [comment]
This update will be available on Homey v5.0.0 and higher.

**Comment by weusthofm** [comment]
Hello,

I've got homey version 4.2.0.
How can I upgrade to version 5.0.0.

Marcel

Verzonden vanaf mijn Huawei-telefoon


-------- Oorspronkelijk bericht --------
Van: Robin Bolscher <notifications@github.com>
Datum: vr 19 jun. 2020 08:41
Aan: "athombv/com.ikea.tradfri" <com.ikea.tradfri@noreply.github.com>
Cc: "Weusthof, M.H.H. (EEMCS)" <m.h.h.weusthof@utwente.nl>, Comment <comment@noreply.github.com>
Onderwerp: Re: [athombv/com.ikea.tradfri] feat: update to SDKv3 (#92)

This update will be available on Homey v5.0.0 and higher.

**Comment by RobinBol** [comment]
It is currently not yet available, once it is released you will see the available update in Settings > Updates.

**Comment by chriss10an** [comment]
hi, 

Great work so far!

do we have any date for this update ?

**Pull request merged**
