### PR TITLE
Control outlet support

### PR DESCRIPTION
**Pull request by JohanBendz**
Hi Robin.
Added support for the new Control Outlet.

// Johan

### CODE REVIEW

**Comment by JohanBendz** [comment]
Hi again. Yes, the Control Outlet has already been released in limited numbers in some of the IKEA stores in Sweden. So I have a few and have verified the functionality.

The Control Outlet can be added as a generic zigbee device and work nice that way too.

Yeah, sorry about the transformer, I did not notice it was added to the pull request. 

// Johan

**Comment by nhassink** [comment]
The control outlets are also available in the Netherlands. Just bought 2 in Zwolle. Would be great if these can be added to the Ikea app. If you need a tester let me know.

**Comment by ruudmens** [comment]
Put Ikea Haarlem on the list to, just bought one there. They had enough in store. Would love to see these in the app

**Comment by RobinBol** [comment]
@JohanBendz thanks again for your PR, I took some parts of the code and created a new PR (without the transformer changes) here: https://github.com/athombv/com.ikea.tradfri/pull/51

So I will close this PR, expect the changes to be pushed to the beta channel in the app store soon!

**Pull request closed without merging**
